### ISSUE TITLE
Error starting server

### ISSUE THREAD

**Issue by mrbernnz** [sneakyhead/sneakyhead#26]
Trying to setup my workspace, but I need to know what steps I should take. cc/ @snuggs @RobertChristopher 

![screenshot 2015-12-25 16 27 38](https://cloud.githubusercontent.com/assets/9615028/12004412/cb70ce20-ab24-11e5-8953-fd87d31c60ea.png)

**Comment by snuggs** [comment]
Not all tests are running @mrbernnz and you are correct this IS an issue with the system.

**Comment by RobertChristopher** [comment]
Yes, I believe the Nike code needs some refactoring as it is broken.

**Comment by snuggs** [comment]
@mrbernnz Server works  please review PR https://github.com/sneakyhead/sneakyhead/pull/29

**Comment by snuggs** [comment]
Addressed in #29

**Comment by snuggs** [comment]
Addressed in #29
